// ? уточнить
export const ORDERS_CONNECTON_INIT = 'ORDERS_CONNECTON_INIT';
export const ORDERS_CONNECTON_CLOSE = 'ORDERS_CONNECTON_CLOSE';
export const ORDERS_CONNECTON_SUCCESS = 'ORDERS_CONNECTON_SUCCESS';
export const ORDERS_CONNECTON_CLOSED = 'ORDERS_CONNECTON_CLOSED';
export const ORDERS_CONNECTON_ERROR = 'ORDERS_CONNECTON_ERROR';
export const ORDERS_GET_MESSAGE = 'ORDERS_GET_MESSAGE';
