// ? уточнить
export const ORDERS_CONNECTION_INIT = 'ORDERS_CONNECTION_INIT';
export const ORDERS_CONNECTION_CLOSE = 'ORDERS_CONNECTION_CLOSE';
export const ORDERS_CONNECTION_SUCCESS = 'ORDERS_CONNECTION_SUCCESS';
export const ORDERS_CONNECTION_CLOSED = 'ORDERS_CONNECTION_CLOSED';
export const ORDERS_CONNECTION_ERROR = 'ORDERS_CONNECTION_ERROR';
export const ORDERS_GET_MESSAGE = 'ORDERS_GET_MESSAGE';
