// actions/burger.ts
export const CONSTRUCTOR_ADD_INGREDIENT: 'CONSTRUCTOR_ADD_INGREDIENT' =
  'CONSTRUCTOR_ADD_INGREDIENT';
export const CONSTRUCTOR_REMOVE_INGREDIENT: 'CONSTRUCTOR_REMOVE_INGREDIENT' =
  'CONSTRUCTOR_REMOVE_INGREDIENT';

export const CONSTRUCTOR_ADD_BUN: 'CONSTRUCTOR_ADD_BUN' = 'CONSTRUCTOR_ADD_BUN';
export const CONSTRUCTOR_REMOVE_BUN: 'CONSTRUCTOR_REMOVE_BUN' = 'CONSTRUCTOR_REMOVE_BUN';

export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR_REORDER' = 'CONSTRUCTOR_REORDER';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET' = 'CONSTRUCTOR_RESET';

export const ORDER_SAVE_REQUEST: 'ORDER_SAVE_REQUEST' = 'ORDER_SAVE_REQUEST';
export const ORDER_SAVE_SUCCESS: 'ORDER_SAVE_SUCCESS' = 'ORDER_SAVE_SUCCESS';
export const ORDER_SAVE_FAIL: 'ORDER_SAVE_FAIL' = 'ORDER_SAVE_FAIL';

// actions/feed.ts
export const FEED_CONNECTION_INIT: 'FEED_CONNECTION_INIT' = 'FEED_CONNECTION_INIT';
export const FEED_CONNECTION_CLOSE: 'FEED_CONNECTION_CLOSE' = 'FEED_CONNECTION_CLOSE';
export const FEED_CONNECTION_SUCCESS: 'FEED_CONNECTION_SUCCESS' =
  'FEED_CONNECTION_SUCCESS';
export const FEED_CONNECTION_ERROR: 'FEED_CONNECTION_ERROR' = 'FEED_CONNECTION_ERROR';
export const FEED_CONNECTION_CLOSED: 'FEED_CONNECTION_CLOSED' = 'FEED_CONNECTION_CLOSED';
export const FEED_GET_MESSAGE: 'FEED_GET_MESSAGE' = 'FEED_GET_MESSAGE';

// actions/ingredientDetails.ts
export const INGREDIENT_MODAL_OPEN: 'INGREDIENT_MODAL_OPEN' = 'INGREDIENT_MODAL_OPEN';
export const INGREDIENT_MODAL_CLOSE: 'INGREDIENT_MODAL_CLOSE' = 'INGREDIENT_MODAL_CLOSE';

// actions/ingredients.ts
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAIL: 'GET_INGREDIENTS_FAIL' = 'GET_INGREDIENTS_FAIL';
export const SET_INGREDIENT_COUNTER: 'SET_INGREDIENT_COUNTER' = 'SET_INGREDIENT_COUNTER';
export const INCREASE_COUNTER: 'INCREASE_COUNTER' = 'INCREASE_COUNTER';
export const DECREASE_COUNTER: 'DECREASE_COUNTER' = 'DECREASE_COUNTER';

// actions/order.ts
export const ORDER_MODAL_OPEN: 'ORDER_MODAL_OPEN' = 'ORDER_MODAL_OPEN';
export const ORDER_MODAL_CLOSE: 'ORDER_MODAL_CLOSE' = 'ORDER_MODAL_CLOSE';

// actions/orders.ts
export const ORDERS_CONNECTION_INIT: 'ORDERS_CONNECTION_INIT' = 'ORDERS_CONNECTION_INIT';
export const ORDERS_CONNECTION_CLOSE: 'ORDERS_CONNECTION_CLOSE' = 'ORDERS_CONNECTION_CLOSE';
export const ORDERS_CONNECTION_SUCCESS: 'ORDERS_CONNECTION_SUCCESS' = 'ORDERS_CONNECTION_SUCCESS';
export const ORDERS_CONNECTION_CLOSED: 'ORDERS_CONNECTION_CLOSED' = 'ORDERS_CONNECTION_CLOSED';
export const ORDERS_CONNECTION_ERROR: 'ORDERS_CONNECTION_ERROR' = 'ORDERS_CONNECTION_ERROR';
export const ORDERS_GET_MESSAGE: 'ORDERS_GET_MESSAGE' = 'ORDERS_GET_MESSAGE';

// actions/password-reset.ts
export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL' = 'PASSWORD_RESET_FAIL';

// actions/password-restore.ts
export const PASSWORD_RESTORE_REQUEST: 'PASSWORD_RESTORE_REQUEST' = 'PASSWORD_RESTORE_REQUEST';
export const PASSWORD_RESTORE_SUCCESS: 'PASSWORD_RESTORE_SUCCESS' = 'PASSWORD_RESTORE_SUCCESS';
export const PASSWORD_RESTORE_FAIL: 'PASSWORD_RESTORE_FAIL' = 'PASSWORD_RESTORE_FAIL';

// actions/user.ts
